[Draft] Allow the user to make moves
marmelab/15-puzzle-cli pull request #3
Opened 2017-10-12 15:00 UTC by Luwangel

Choose the piece to move towards the empty place.
- Using the letters (T)op, (R)ight, (B)ottom, (L)eft
- Using the arrow keys
The puzzle must update according to the piece I moved

- [x] Optimize the docker build
- [x] Create the move function
- [ ] Manage errors
- [x] Write the main loop
- [ ] Create the gui (display, ask user commands)

2017-10-12 15:23 UTC, Kmaschta commented on src/game.py
> +    else:
Nope, handle LEFT here. If direction is not one of the four, raise an exception

2017-10-12 15:23 UTC, Kmaschta commented on src/renderer.py
> +    if direction == 'T':
You can handle miniscules too

2017-10-12 15:56 UTC, jdemangeon commented on src/renderer.py
> +    grid_to_show = '\n___________________\n\n'
You can use multiply on string in python. 
Eg: '\n' + ('_' * grid) + '\n'

2017-10-13 06:24 UTC, jdemangeon approved these changes

2017-10-13 06:24 UTC, jdemangeon commented
Tests fail

2017-10-13 07:25 UTC, Kmaschta reviewed
Can you add a constant somewhere `EMPTY_TILE = Null` ?

In this way, you can check that way: `game[x][y] is EMPTY_TILE`

2017-10-13 07:25 UTC, Kmaschta commented on src/game.py
> +from enum import Enum
Is this Enum really useful ?

2017-10-13 07:25 UTC, Kmaschta commented on src/game.py
> +    if empty_tile == [-1, -1]:
This is an impossible case

2017-10-13 07:27 UTC, Kmaschta commented on src/game.py
> +    if direction not in possible_moves(grid) or empty_tile == [-1, -1]:
Don't manage impossible case

2017-10-13 07:28 UTC, Kmaschta commented on src/game.py
> +    TOP = 1
You don't have to use numbers here. Use strings `TOP = 'TOP'`, it's easier to debug

2017-10-13 07:30 UTC, Kmaschta commented on src/game.py
> +        raise Exception('The direction provided to the move function is not allowed')
Use a custom exception here

2017-10-13 07:33 UTC, Kmaschta commented on src/test_game.py
> +        self.assertEqual(build_grid(), [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 0]])
Can you format your matrix?

2017-10-13 07:35 UTC, Kmaschta commented on src/game.py
> +    value = grid[empty_tile[0]][empty_tile[1]]
Don't mutate the grid !
Create a new one

2017-10-13 09:49 UTC, Kmaschta requested changes
Don't forget to handle KeyboardInterrupt

2017-10-13 09:49 UTC, Kmaschta commented on src/game.py
> +from game_exception import MoveException, NoEmptyTileException
I would prefer `from .exception`

2017-10-13 09:49 UTC, Kmaschta commented on src/game.py
> +    new_grid = grid.copy()
:+1:

2017-10-13 10:11 UTC, Kmaschta approved these changes

2017-10-13 10:11 UTC, Kmaschta commented on src/game/game.py
> +    if not empty_tile[0] == 0:
Can you have a constant `EMPTY_TILE` ?

2017-10-13 13:35 UTC, Kmaschta approved these changes

2017-10-13 13:35 UTC, merged