[RFR] Change the puzzle size
marmelab/15-puzzle-cli pull request #9
Opened 2017-10-17 11:13 UTC by Luwangel

- [x] Offer a (W)idth command to change the grid width
- [x] Improve some UI

2017-10-17 13:50 UTC, Luwangel commented
![peek 17-10-2017 15-49](https://user-images.githubusercontent.com/5584839/31668587-e3ab1648-b352-11e7-8030-1058d024c10d.gif)

2017-10-17 14:35 UTC, Kmaschta requested changes

2017-10-17 14:35 UTC, Kmaschta commented on src/game/exception.py
> +class SizeNotValidException(GameRuleException):
Size of what?

2017-10-17 14:35 UTC, Kmaschta commented on src/game/game.py
> +    if not MIN_SIZE <= size <= MAX_SIZE:
Can you test the upper and lower bound error ?
I don't see this error on the test

2017-10-17 14:35 UTC, Kmaschta commented on src/index.py
> +                if not min_size <= size <= max_size:
Duplicated code from build grid. You better have to check for invalid size exception

2017-10-17 14:35 UTC, Kmaschta commented on src/renderer/renderer.py
> +    return 'You are allowed to move (%s)' % ', '.join(str(tile) for tile in movable_tiles)
```diff
-str(tile) for tile in movable_tiles
+movable_tiles.map(str)
```

2017-10-18 07:27 UTC, Kmaschta commented on src/index.py
> +        return [new_grid, new_grid.copy(), False]
Not mandatory for this PR but in this kind of function, we prefer return an object with named attributes.

2017-10-18 07:27 UTC, Kmaschta approved these changes

2017-10-18 07:27 UTC, merged